import fs from 'node:fs';
export const PERIOD=JSON.parse(fs.readFileSync(new URL('./report_config.json',import.meta.url),'utf8').replace(/^\uFEFF/,''));
const semantic=JSON.parse(fs.readFileSync(new URL('./ai_semantic_analysis.json',import.meta.url),'utf8'));
export const ALL_PR_ANALYSIS=Object.fromEntries(Object.entries(semantic).map(([k,v])=>[k,[...v.slice(0,3),v[3]?'是':'否']]));
export const localTimestamp=s=>new Date(Date.parse(s)+8*3600000).toISOString().slice(0,23).replace('T',' ');
export const localDate=s=>localTimestamp(s).slice(0,10);
export const BUGFIX_CONFIG={
57867:['MoE hash路由能力','不受影响','魏谨谦','Ascend patch_fused_moe.py构造自有router并传tid2eid，ops/fused_moe/router执行NPU路由；不选择被拒绝的CUDA/ROCm monolithic专家。保留hash协议回归，不能按共同MoE文件推定缺陷。'],
57866:['AITER EP专家映射','不受影响','魏谨谦','AITER MXFP4 W4A16/W4A8是ROCm后端；NPU采用自有量化和专家分发，不执行其monolithic专家索引。'],
57871:['CPU镜像子模块','不受影响','邵圣珂','仅上游CPU Dockerfile中triton-cpu的sleef检出；Ascend独立Docker/AscendC构建不走该CPU镜像stage。'],
57984:['SwiGLU clamp丢失','不受影响','王锟鹏','修复限定TritonExperts block128融合量化；Ascend注册自有FusedMoE/量化实现，不运行silu_and_mul_per_block_quant。NPU clamp支持另属模型能力，不由此证明。'],
57737:['MRV2 pooling引用释放','直接继承修复','郭小辉','worker/v2/model_runner.py的NPUModelRunner继承GPUModelRunner，未重写shutdown；worker.shutdown调用runner关闭，清空共享pooling_runner进入。',{verification:'保留LLM/worker对象，调用shutdown后查模型weakref与torch.npu.memory_allocated；embedding输出和多次关闭回归。'}],
55390:['MTP KV分组注解','需要适配','曾彦嘉','patch_kv_cache_utils.py:_ascend_get_packed_kv_cache_groups仍以use_deepseek_v4_fallback=True调用共享_annotate_eagle_groups；目标上游已改名为use_trailing_layer_fallback，packed NPU分组会触发意外关键字TypeError。通用分组经原函数可继承，但不可覆盖此断点。',{verification:'同步关键字并按_uses_trailing_mtp_layers及精确partition约束确定值，覆盖DSV4/4.1 DSpark、Qwen hybrid MTP、目标/draft共享组、多组draft及offload尾块。',priority:'P1'}],
51565:['GDN首块状态','不受影响','龙钢','AscendGDNAttentionMetadataBuilder自有build已设置treat_short_extends_as_decodes=False，共享split会结合m.is_prefilling，将无状态首块归入prefill。修复不直接进入，但已防止本PR的非投机首块误读；不要扩展为所有混合spec场景已验证。',{reachable:'是',equivalent:'是',verification:'复用旧状态页执行一token首块、续块与ACLgraph dummy；另外覆盖混合spec零draft路径，不把上游16个UT当NPU验证。'}],
49685:['XPU评测后端','不受影响','张新悦','仅Intel Buildkite与XPU评测yaml；Ascend独立nightly/CI模型配置不消费这项CUDA-only覆盖。'],
57606:['CUDA镜像Rust入口','不受影响','张新悦','修改上游CUDA Dockerfile的vllm-base，Ascend独立镜像不直接继承此RUN；若交付Rust入口应在NPU镜像做PATH专项检查。'],
57312:['IPC draft缓存路由','不受影响','徐驰','上游weight_cache/protocol.check_ipc_platform_support只允许is_cuda_alike；NPU不走CUDA IPC loader，现有rfork和NPU IPC权重传输不是此daemon协议。优化思想另列POC。'],
57933:['Rust MiMo模板解析','待确认','冀元祎','变更位于Rust parser/chat和模板发现；Ascend以共享Python服务为主，pinned源码无法证明实际部署已使用Rust MiMo入口。共享Rust前端能力可承接，但可达性须确认。',{evidenceLevel:'E1',verification:'先确认NPU部署是否启用vllm-rs及MiMo模型；对真实模板运行reasoning/tool流式往返、None schema与root模板优先级测试。'}],
56448:['DSpark/DFlash profiling越界','直接继承修复','李泽桐','NPUModelRunner.profile_run与_dummy_run均调用super，MRV2 request上限修复进入；NPU DSpark/DFlash子类保留num_query_per_req。最终merge仅初始dummy cap，不能宣称所有autotune/profile路径全覆盖。',{verification:'max_num_seqs512/max_num_batched_tokens2048/K5及DFlash2 K7/512token启动；检查MC2额外dummy、ACLgraph padding与真实请求边界。'}],
57891:['RL冻结参数睡眠','需要适配','刘荣','Ascend worker.py自有sleep/wake_up，仅备份named_buffers，CaMemAllocator level2丢弃weights；未读取新sleep_preserve_parameter_names，也无named_parameters备份。trainer省略冻结参数时缺口确定。',{verification:'在NPU sleep前按glob备份选中参数、weights wake原位恢复并释放；验证未匹配报错、CPU权重、三轮sleep、图地址稳定及host容量，trainer必须不覆盖保留权重。',priority:'P1'}],
57919:['ROCm FSE/DPA配置','不受影响','曾彦嘉','只修改deepseek_v4/amd/model.py；NPU模型注册为vllm_ascend.models.deepseek_v4，专家与共享专家方案不同，不执行ROCm FSE门禁。'],
57731:['请求参数准入安全','直接继承修复','刘逸舟','NPU未替换vllm.v1.engine.input_processor.InputProcessor；共享前端填充max_tokens后的边界检查进入NPU请求准入。',{priority:'P1',verification:'max_tokens=null且min_tokens越界返回客户端错误，再发正常请求确认engine存活；覆盖离线和HTTP。'}],
57006:['混合embedding mask','直接继承修复','刘逸舟','NPU前端使用共享InputProcessor，未覆盖新增mask长度校验；在NPU runner接收前拒绝不等长mask。',{verification:'embedding3行配mask长度0/1/2/4拒绝，3合法；纯embedding、带token混合及拒绝后的正常请求回归。'}],
47736:['Qwen2.5VL视频MRoPE','直接继承修复','龙钢','Ascend采用共享Qwen2.5VL多模态processor，NPU模型算子/ViT patch未替换视频parser和HF metadata传递；时间尺度修复进入。',{verification:'同视频fps1/30检查second_per_grid_ts和MRoPE，裸数组无metadata应报错；视频dummy与图捕获回归。'}],
55931:['结构化grammar阻塞轮询','直接继承修复','温劲','Ascend patch_structured_output包装SamplingParams与StructuredOutputManager，未覆盖StructuredOutputRequest._check_grammar_completion；共享done/result逻辑进入所有相关scheduler。',{verification:'未完成Future不阻塞；已完成且抛TimeoutError应结束为失败，不能永久等待。积压数递增测schedule时长和请求隔离。'}],
47450:['空结构化tag校验','直接继承修复','温劲','patch_structured_output._validate_structured_outputs首先调用original_validate，新增空structural_tag检查仍有效。PR另有Ascend实测描述，但不是本次pinned baseline实测。',{verification:'空structural_tag返回400，正常json_object返回200，合法空regex不误拒绝；引擎后续请求正常。'}],
57945:['CUDA12依赖冲突','不受影响','邵圣珂','CUDA Docker/CI connector安装依赖与NPU torch_npu/CANN包栈不同；不能将CuPyCUDA12/LMCache版本直接带入Ascend镜像。'],
58061:['GLM5Next SP dense MLP','不受影响','毛琦','NPU glm5next/model.py dense MLP已传is_sequence_parallel=self.is_sequence_parallel及reduce_results=not self.is_sequence_parallel；其linear以disable_tp控制分片，已具同类保护。',{reachable:'是',equivalent:'是',verification:'TP2/DP2/EP混合长短请求核对dense层token归属、权重完整性、首token和输出异常率，防止后续覆盖丢失已有保护。'}],
56250:['MRV1 PP异步配置','直接继承修复','田馥玮','Ascend patch_use_v2_model_runner的V1 unsupported wrapper调用原函数，只移除dspark和dflash2条目，不移除pipeline parallelism with async scheduling；新拒绝生效，自动异步关闭也在共享配置。',{verification:'NPU默认V1的PP>1自动async关闭，显式async应拒绝；PP1/MRV2组合单独回归，不能把PR正文过时的禁所有PP解释为最终行为。'}],
55881:['XPU batch invariant','不受影响','温捷','XPU平台MoE门禁与XCCL communicator不在Ascend执行链；NPU自有HCCL和确定性机制。固定rank归约可做方法参考，不代表NPU已满足逐bit一致。'],
58150:['AuxOutput connector门禁','直接继承修复','周学荣','共享VllmConfig使用KVTransferConfig.has_connector，Ascend无该AuxOutput校验覆盖。NPU自有PD connector名字未列入五项，放行不证明支持；前窗R3接口缺口仍需先解决。',{verification:'直接及MultiConnector覆盖Mooncake/Nixl拒绝、offload放行；对Ascend自有PD连接器补能力策略并验证KV/R3联合恢复，避免门禁放宽导致错误启用。'}],
58073:['DeepGEMM能力短路','直接继承修复','王锟鹏','共享is_deep_gemm_supported能力查询先判is_supported_arch，NPU不符合CUDA架构即短路；Ascend未覆盖此helper。这是避免导入/警告，不是支持DeepGEMM内核。'],
56579:['Triton softcap数值溢出','不受影响','赵可瑞','修复上游Triton unified/DiffKV/INT4 attention helper；NPU platform选择Ascend backend及自有算子，不调用该helper。需避免用此结论替代NPU softcap能力验证。'],
57914:['Engram SHM能力检测','不受影响','王小超','can_share_engram_tables只由NVIDIA模型调用，NPU模型不执行该disk_usage自动探测。当前AscendEngramConfig的dp_shared_memory默认False，显式启用时走自有SharedUvaBuffer并广播创建失败；不是上游自动共享回退方案。',{verification:'无/dev/shm时分别验证默认非共享能启动、显式共享给出一致错误而非rank挂起。若增加NPU自动共享，借鉴能力检测与容量不足回退；不声称当前NPU已具自动回退。'}],
43462:['CUDA Hadamard别名','不受影响','王锟鹏','修复CUDA hadacore及compressed-tensors在线QuIP；NPU使用自有Hadamard/量化算子，不调用该CUDA编译产物。可借鉴输入输出alias契约测试。']
};
export const BUGFIX_IDS=Object.keys(BUGFIX_CONFIG).map(Number);
export const FEATURE_CONFIG={
57937:['Engram配置移除','直接继承','韩俊','共享env入口删除进入；NPU Engram采用自身host实现，不应再用旧环境开关控制。','排查部署脚本VLLM_PLE_CPU_OFFLOAD，迁移至显式EngramConfig并核对NPU能力。'],
55390:['KV分组关键字变更','需要适配','曾彦嘉',BUGFIX_CONFIG[55390][3],BUGFIX_CONFIG[55390][4].verification],
57891:['冻结权重保留配置','需要适配','刘荣',BUGFIX_CONFIG[57891][3],BUGFIX_CONFIG[57891][4].verification],
58065:['DFlash异步组合','待验证','李泽桐','共享allowlist进入，但Ascend默认仍是V1，另有NPU DFlash/V2实现；不能把上游默认MRV2视为NPU默认。','分别显式开启V2和V1测试异步输出/拒绝采样，记录支持矩阵，不支持组合明确拒绝。'],
57312:['draft缓存角色','当前不适用','徐驰',BUGFIX_CONFIG[57312][3],'若扩展NPU权重缓存，单独设计target/draft指纹与tensor共享协议，不能复用CUDA IPC句柄。'],
51360:['初始化快照CLI','当前不适用','徐驰','新增snapshot依赖CRIU CUDA plugin及单Nvidia GPU；NPU rfork只是权重共享，不是进程快照等价实现。','保留NPU既有loader；先评估驱动/进程恢复能力，再规划独立POC。'],
54867:['测试覆盖门禁','需要适配','张新悦','Ascend使用独立CI/workflows而非上游Buildkite job目录；测试与执行命令关联检查不会自动进入。','适配本仓CI命令解析，建立测试文件到job映射；覆盖wrapper、过滤参数、白名单失效与新增漏挂测试。'],
57933:['Rust MiMo协议','待验证','冀元祎',BUGFIX_CONFIG[57933][3],BUGFIX_CONFIG[57933][4].verification],
51922:['Rust多模态基准','待验证','龙钢','Rust前端新增基准不等同NPU Python前端工具；与headless NPU engine联调尚无本次证据。','验证NPU headless启动/关闭和阶段计时，保持计时默认关闭，勿当性能优化收益。'],
55269:['Rust grammar接口迁移','待验证','温劲','Rust新trait及tokenize后初始化不修改NPU Python parser；外部Rust集成消费者是否使用旧trait需部署侧确认。','使用最终prompt tokens调用initialize再build_output_grammar，初始化失败应在提交前返回。'],
57340:['完整输出grammar','待验证','温劲','依赖同窗#55269，仅指定Rust parser开启FromTokenZero；NPU Python reasoning逻辑不自动变为Rust语法。','在实际Rust+NPU组合验证reasoning闭合、工具调用、截断及不支持模型回退。'],
56547:['设备内存CLI别名','直接继承','韩俊','共享EngineArgs解析别名仍映射gpu_memory_utilization，NPU继续读取同字段。','新旧参数各启动一次，核对内存预算一致；明确同时指定时解析规则。'],
58109:['Rust视觉processor生命周期','待验证','龙钢','只改Rust model spec与Arc所有权，NPU Python processor未迁移；需要实际Rust部署链确认。','对模型切换、图像视频并发及UnsupportedModality测试配置隔离，比较处理结果。'],
56250:['MRV1 PP异步支持收缩','直接继承','田馥玮',BUGFIX_CONFIG[56250][3],BUGFIX_CONFIG[56250][4].verification],
58150:['AuxOutput KV能力策略','需要适配','周学荣','上游仅按五个已知PD名称拒绝，Ascend自有PD connector不在名单；门禁放宽并非NPU KV/R3协议已闭环。','为NPU connector明确AuxOutput能力，未验证的PD组合继续拒绝；完成前窗R3接口迁移后再验联合恢复。'],
57428:['GEMM-RS环境开关','当前不适用','毛琦','旧VLLM_KIMI_K3_GEMM_RS合并为VLLM_ENABLE_GEMM_RS控制SM100内核；NPU自有HCCL路径不消费该内核开关。','部署若保留旧GPU脚本须更新；NPU GEMM通信融合走独立配置与能力门禁。']
};
export const FEATURE_IDS=Object.keys(FEATURE_CONFIG).map(Number);
const raw=[];
function opt(pr,kind,owner,category,target,point,relation,result,conditions,plan,review,metric='时延、吞吐与资源占用'){
 const modes={direct:['auto-inherit','理论直接继承','直接继承'],adapt:['patch-sync','需要适配','收益明确待适配'],poc:['idea-copy','待POC','收益不明确待验证'],borrow:['idea-copy','待POC','平台差异可借鉴'],skip:['skip','当前不适用','不可用']};
 const [method,final,fiveCategory]=modes[kind];
 raw.push({pr,owner,category,target:kind==='skip'?'none':target,point,relation,result,conditions,plan,review,metric,method,final,fiveCategory,value:kind==='skip'?'none':'medium',priority:kind==='adapt'?'P1':kind==='skip'?'skip':'P2',secondaryCategory:kind==='borrow'?'硬件相关：平台实现不同，思路可验证':kind==='skip'?'平台路径不支持或无新增收益':kind==='adapt'?'硬件无关：自有覆盖缺少上游机制':kind==='direct'?'硬件无关：共享路径进入，NPU收益待验证':'有效路径或实际瓶颈待验证',valueReason:relation,patch:kind==='adapt',patchKeys:kind==='adapt'?[pr===57951?'vllm.v1.core.sched.scheduler':'vllm.v1.worker.gpu_worker']:[],evidenceLevel:pr===58109?'E1':'E2'});
}
opt(54185,'borrow','魏谨谦','moe-fusion','csrc/moe','共享专家gate采用平台优化GEMM分派','NPU FusedMoEFactory创建自有router/expert，ROCm dispatcher不会提供NPU快核；可在NPU gate projection评估小矩阵选核。','上游C4吞吐279.6→289.4 token/s（+3.5%）；全并发几何均值仅+0.5%。gate kernel约2倍不等于整模2倍。','8×MI355X，Qwen3.8-2.4T-A95B MXFP4、TP8，输入/输出1024，并发4/8/16/32/128；基线1轮、候选3轮中位。','profile NPU gate投影shape与launch，比较现有linear和优化GEMM分派；覆盖低高并发与量化精度。','收益集中低并发；不能因共享MoERunner类便宣称NPU自动加速。');
opt(55608,'poc','张新悦','test-ci','python-adapter','镜像zstd压缩缩短拉取与首次响应','Ascend独立Docker/镜像发布工作流不继承上游构建参数；压缩方法跨硬件，但NPU运行时兼容和网络/CPU瓶颈需测量。','上游字节8,664,824,384→6,999,776,144（-19.2%）；首次正确响应中位144.51→118.02秒，配对节省22.19秒。','RTX4090 Laptop、本地registry、Qwen3-0.6B、4CPU，每轮新store，3轮；这是镜像冷启动，不是decode吞吐。','在Ascend发布链增加可选zstd变体，先验证Docker/containerd/Enroot及镜像扫描兼容，测真实远端拉取到首响应。','gzip保留；Docker20/Enroot3.5等旧运行时存在兼容风险，不能统一替换。','镜像大小、拉取解压及首次响应时间');
opt(50592,'borrow','龙钢','model-architecture','python-adapter','Kimi attention直接返回结果，减少输出搬运','AscendKimiDecoderLayer._run_self_attn已直接return self.self_attn；NPU无需迁移AMD output缓冲接口。AMD prefix_delta和剩余NPU norm/copy可另做profile，不能重复计已有直接返回收益。','上游C16 TPOT73.141→72.428ms、吞吐193.575→195.555；C24吞吐278.245→280.452（+0.79%）。','8×MI355X Kimi-K3 BF16/MXFP4、TP8，无投机，prefix63911+4089输入、输出1024，C16/24；1预热3轮。','NPU按attention返回、KDA norm copy及残差prefix_sum分别抓trace，仅优化真实多余copy；校验残差捕获与ACLgraph地址。','不要重做NPU已有返回值方案；93个copy删除统计是AMD路径，不是NPU测量。');
opt(51360,'borrow','徐驰','core-engine','python-adapter','初始化快照减少进程重建激活时间','CUDA CRIU checkpoint不能用于NPU；Ascend rfork处理权重共享不等同进程恢复。可借鉴初始化阶段拆分、指纹和恢复oracle，但需NPU驱动恢复能力POC。','历史H100 Qwen3-32B激活54.7029→20.3795秒（-62.7%，各3样本）；非最终H200镜像时延结论。','H100 PCIe80GB、Qwen3-32B BF16 TP1，model/cache驻留，artifact逐次驱逐，各3次；H200仅生命周期验收。','先验证NPU进程/allocator/流可恢复边界，隔离可复用CPU初始化；建立同版本指纹、token oracle与失败清理，不直接调用CUDA checkpoint。','仅同机Linux x86_64 TP1，特权artifact含内存秘密；最终性能与历史测试SHA必须区分。','冷激活时延、快照大小和恢复正确性');
opt(57737,'direct','郭小辉','core-engine','none','shutdown解除pooling模型引用',BUGFIX_CONFIG[57737][3],'上游H100 MiniLM保留allocated 80,732,672→33,801,728字节，约释放47MB；weakref由存活变释放。','H100、all-MiniLM-L6-v2、MRV2 pooling、eager、maxlen64；关闭多进程，保留LLM对象后shutdown；非吞吐测量。',BUGFIX_CONFIG[57737][4].verification,'只在关闭生命周期获益，不能写为运行中KV容量或推理吞吐提升。','shutdown后allocated与模型引用');
opt(57965,'poc','吴文俊','test-ci','python-adapter','评测按模型拆job缩短CI关键路径','Ascend有独立nightly/CI资源池，不执行H200 Buildkite job。方法可跨平台迁移，但排队和多job加载成本须测。','旧job wall41–75分钟；新最慢pytest18.6分钟来自旧日志分项预测，非新流水线实测；总worker-min约72→82亦为估算。','六项DeepSeek/Nemotron GSM8K，原8×H200串行；拆五job可占40卡，基于四个main build日志估算，AMD不变。','按Ascend nightly实际耗时拆最慢模型组，确认用例不重不漏、并发卡预算与排队时间；同时报告总卡时。','不能把预计最长job缩短直接填为CI实测节省。','CI关键路径、排队和总卡时');
opt(57951,'adapt','姜凯强','scheduler','python-adapter','单请求prefill取消不必要阈值分块','Ascend BalanceScheduler及DyntraLB/Recompute/ProfilingChunk自有schedule仍无条件应用long_prefill_token_threshold；platform能选这些类。默认共享路径可继承，覆盖路径相同空耗仍存在，需同步。','PR仅185个测试通过，未提供TTFT/吞吐A/B；删除闲置token预算限制的机制明确，NPU收益数值未测。','调度单元测试覆盖单请求与多请求；硬件、模型、输入输出与服务benchmark未披露。','在各有效schedule统一计算running+waiting+skipped_waiting是否>1，再用于running/waiting两分支；保留ProfilingChunk额外预算和PD约束，回归公平性及TTFT。','不是所有chunk限制都删除；max_num_batched_tokens和专用调度预算仍有效。','单请求TTFT、每步实际token数和多请求公平性');
opt(57458,'borrow','朱意霖','attention-kv-cache','csrc/attention','NoPE sparse MLA融合索引准备与消除空cat','Ascend使用dsa_v1、自有indexer及NPU MLA算子，不进入FlashInfer safe_lengths/remap CUDA链；可借鉴单tile计数填充融合及空rope旁路。','上游32K prefill TTFT518.25→507.61ms（-2.05%）；decode ITL122.85→120.77ms（-1.70%）。','4×GB300，GLM-5.3-Flash TP4/EP4 eager，FP8 KV，无prefix/投机；输入32768，输出1/128；4交替轮各5对。','NPU profile index remap、fill、计数及query concat；确认零行与DCP局部选择语义再融合，覆盖2176/4096及大容量回退。','旧微基准和最终服务A/B口径不同；不能删除NPU需要的空行mask。');
opt(57312,'borrow','徐驰','core-engine','python-adapter','draft独立daemon缓存避免重复加载',BUGFIX_CONFIG[57312][3],'PR未提供加载时延或内存A/B；只记录缓存角色隔离与避免重复加载机制。','上游CUDA-alike IPC loader、target与draft同TP；最终方法集合mtp/eagle/eagle3，未披露硬件模型及轮次。','结合Ascend rfork/NPU IPC loader评估独立draft缓存key与生命周期，校验别名/ownership flag、socket冲突和不支持draft回退磁盘。','以最终diff为准，不沿用正文MTP-only和_draft0.sock描述。','draft加载耗时、磁盘读取量和缓存命中');
opt(57891,'adapt','刘荣','core-engine','python-adapter','睡眠保留冻结参数，减少不必要权重重传',BUGFIX_CONFIG[57891][3],'上游GB200三次level2循环保留lm_head全部16,384字节和data_ptr；未给重传时延收益。VERL的202.758GB CPU驻留是保留正确性，非节省量。','GB200小Llama三轮sleep/wake；另有8rank VERL及两主机TP8集成，输入输出/并发非性能A/B口径。',BUGFIX_CONFIG[57891][4].verification,'明确功能适配必须完成；收益方向为免传冻结参数，不声称NPU已提速或节省全部CPU驻留量。','冻结参数传输量、sleep/wake耗时和host峰值');
opt(58065,'poc','李泽桐','spec-decode','python-adapter','允许DFlash异步调度以重叠CPU工作',FEATURE_CONFIG[58065][3],'上游bs1 TPOT2.127→1.510ms，decode470.2→662.3token/s（约+41%）；采用合成接受长度6。','4×GB200 Qwen3.8-27B+DFlash2，TP4、draft TRITON_ATTN全图；输入1输出1000、并发1，2预热4请求。',FEATURE_CONFIG[58065][4]+'比较真实接受率与合成口径，测低高并发TPOT/P99。','配置放行不等于NPU组合可用；上游额外关闭allreduce-rms融合并使用特定draft后端。');
opt(47842,'poc','曾彦嘉','operator-kernel','python-adapter','GDN norm保留原rank以消除编译reshape copy','Ascend ops/gdn.py自有forward仍reshape为2D再norm/rearrange；AscendRMSNormGated走LayerNormFn而非AITER fusion。代码不自动进入，但reshape是否产生设备copy须NPU profile。','上游MI355X C4/16/64吞吐分别+0.8%/+0.5%/+0.4%，每点仅一次；216 norm测试通过。','8×MI355X Qwen3.8-2.4T-A95B MXFP4 TP8，输入/输出1024，C4/16/64；同commit stock比较。','记录NPU norm输入stride/shape和设备trace，验证LayerNormFn的3D语义，再移除真正产生copy的reshape；同时回归量化与ACLgraph。','最终diff是共享Qwen代码，不应按ROCm标题直接skip；NPU独立forward仍需验证。');
opt(50814,'borrow','王锟鹏','quantization','csrc/quantization','仿真权重加载时一次反量化换取推理少计算','NPU采用自有量化方法和算子，未进入上游EmulationMxfp4LinearKernel；可对确有逐步反量化的NPU回退路径借鉴，不能扩大BF16内存而忽视KV容量。','历史C1 emulation TPOT402.43→90.97ms，C4 177.14→109.98ms；不是当前head独立A/B，C16等无对应基线。','历史MI355X Kimi-K3 MXFP4 TP8；旧runtime与新AITER结果不同，不混算。PR未完整披露输入输出及各轮次。','先找NPU重复反量化回退，比较加载展开与融合反量化GEMM；同时测权重驻留、KV预算、TTFT/TPOT和精度，默认保持关闭。','原生MXFP4与MoE无变化；新runtime相对BF16的1.93%不能归因本开关。');
opt(57428,'borrow','毛琦','distributed','fallback_comm','GEMM与SP reduce-scatter融合减少往返','NPU DSV4.1模型使用自有wo_b/通信与HCCL，不执行SM100 CuTe multicast kernel；计算通信融合边界可借鉴，但布局/精度及同步须重做。','上游M2048算子100.9→63.5微秒（-37.1%）；M128反而+9.7%。服务8K/1K C32吞吐+2.9%，波动接近收益。','4×B200 DSV4.1 TP4/EP4，MXFP8、FP8 KV，无投机；算子40样本；服务8K/1K C16/32各两轮对照。','NPU量测wo_b和HCCL独立耗时与下界，按token数选择融合/回退；验证TP/EP/SP、padding、舍入和图同步，服务至少多轮交替。','小batch融合会回退，不能把算子37.1%当整模收益；1K/2K服务差异被高波动覆盖。');
opt(58097,'borrow','张新悦','test-ci','python-adapter','构建symbol映射与运行trace联合缩小测试集合','上游cuobjdump/fatbin专属CUDA，Ascend使用AscendC/Triton-NPU和不同CI。可借鉴构建产物到测试的动态覆盖关联，不直接套用GPU symbol工具。','上游62秒生成映射，10,447 kernel符号；示例选择6个job并剔除176个。没有实际CI总耗时前后A/B。','CUDA13构建567对象、187个CUDA nightly步骤的运行记录；非模型并发benchmark，默认开关关闭。','为Ascend构建产物和NPU profiler建立源码→算子→测试映射，变更头文件扩大依赖，无映射时全量回退，先影子模式验证漏选率。','不得将无symbol或采集失败解释为无需测试；脚本失败仅输出reason，消费端必须守住回退。','选择测试数、漏选率、映射开销与CI卡时');
opt(55385,'borrow','朱意霖','attention-kv-cache','csrc/attention','NoPE sparse MLA多后端比较与空rope旁路','SM90 FlashMLA/FA3不在NPU平台候选；Ascend自有DSA实现可借鉴NoPE几何专用路径和公平后端对照方法，不能移植FA内核。','修正后FA3吞吐相对FI：32K/512 C32 +2.2%，4K/1K C128 +2.6%；旧16–32%数字作废。','4×H200 GLM-5.3-Flash BF16 TP4，maxlen36000；96/384请求，不同seed预热，每后端两次新服务。','NPU对rope0/head512检查无用拼接和支持门禁；固定max_model_len/prefix/输入长度比较后端，分开host plan与kernel时延。','Review发现长maxlen混淆；FA无prefix组合IMA另立问题，不宣称本PR解决。');
opt(58109,'poc','龙钢','multimodal','python-adapter','视觉processor模型级构造与复用','Rust model spec改为Arc持有processor；NPU Python前端不走Rust生命周期，实际Rust+NPU部署可达性未确认。仅作为构造复用收益候选。','474个chat/text测试通过，依赖382个通过；无构造开销或E2E性能A/B，不用测试数量充当收益。','Rust CPU预处理及真实模型配置golden测试；GPU/NPU生成未验证，硬件/模型并发性能条件未披露。','先确认实际Rust+NPU入口，再测并发图像视频下构造次数、CPU时延和内存；验证模型配置隔离、错误传播与processor线程安全。','这是生命周期重构，不承诺一定提速；在无Rust部署时不算直接承接。');
opt(55931,'direct','温劲','scheduler','none','grammar就绪检查非阻塞，去除逐请求空等',BUGFIX_CONFIG[55931][3],'PR分析473个pending请求×100微秒约47ms/step为理论等待量，非实测加速；2个针对性测试通过。','共享结构化输出Future轮询单测；无硬件、模型、输入输出和服务A/B，理论量按积压数推算。',BUGFIX_CONFIG[55931][4].verification,'正确性与调度等待收益分别管理；done检查不减少grammar编译本身时间。','schedule时长、pending grammar数和请求尾延迟');
const summaries={54185:'ROCm小矩阵分派不进入NPU；可对NPU gate投影评估同类选核。',55608:'NPU镜像链独立，压缩方法可复用；需验证运行时兼容和端到端冷启动收益。',50592:'NPU已直接返回attention结果；仅剩余copy和残差累积思路值得单独评估。',51360:'CUDA进程checkpoint不可直用，NPU可借鉴初始化拆分和恢复oracle。',57737:'NPU MRV2继承共享shutdown，解除pooling引用；关闭后内存收益待NPU回归。',57965:'NPU CI独立；按模型拆分可缩短关键路径，但排队和总卡时需核算。',57951:'NPU多个自有schedule仍无条件限制单请求prefill，需同步放宽门禁。',57458:'NPU不使用FlashInfer路径，可借鉴索引准备融合和空rope旁路。',57312:'CUDA IPC缓存不支持NPU；target/draft角色隔离可借鉴至NPU缓存方案。',57891:'NPU sleep仅保留buffers，缺少冻结参数保留；功能及免重传机制需适配。',58065:'allowlist共享，但NPU默认V1及自有DFlash链需验证，不自动视为组合可用。',47842:'NPU自有GDN保留reshape；是否产生设备copy和净收益需profile。',50814:'NPU量化路径独立，可借鉴一次反量化换计算，需权衡常驻内存与KV容量。',57428:'SM100 GEMM-RS不可直用，可借鉴NPU计算通信融合及按shape回退。',58097:'CUDA symbol工具不可直用，可为NPU建立构建符号与测试动态覆盖映射。',55385:'SM90后端不进入NPU，可借鉴NoPE专用路径与固定上下文的公平对照。',58109:'Rust processor复用机制存在，但实际NPU部署可达性和性能收益未确认。',55931:'NPU共用grammar future轮询，非阻塞修复进入；实际调度收益待测。'};
export const OPTIMIZATIONS=raw.map(d=>({effort:'M',risk:'medium-risk',changeType:'performance',description:semantic[d.pr][0],mechanism:semantic[d.pr][1],...d,valueReason:summaries[d.pr],lowConfidence:d.pr===58109,confidenceReason:d.pr===58109?'未确认实际Rust+NPU部署及构造复用收益':null,verifiedPatchBindings:d.pr===57951?['vllm.v1.core.sched.scheduler.Scheduler.schedule → BalanceScheduler/DyntraLB/Recompute/ProfilingChunk.schedule（当前源码覆盖）']:d.pr===57891?['vllm.v1.worker.gpu_worker.Worker.sleep/wake_up → vllm_ascend.worker.worker.Worker.sleep/wake_up（独立覆盖）']:[],steps:[d.plan],tests:[d.plan]}));
